### ISSUE TITLE
Rack crashing with Tracker

### ISSUE THREAD

**Issue by dromer** [gibbonjoyeux/VCV-Biset#28]
I simply tried loading this module today, but barely got around to look at it.
Latest Rack on Linux, Debian 12.

```gdb
Thread 1 "Rack" received signal SIGSEGV, Segmentation fault.
0x00007fffda11a0c1 in TrackerDisplay::on_key_pattern(rack::widget::Widget::SelectKeyEvent const&) ()
   from /home/dreamer/.Rack2/plugins-lin-x64/Biset/plugin.so
(gdb) bt
#0  0x00007fffda11a0c1 in TrackerDisplay::on_key_pattern(rack::widget::Widget::SelectKeyEvent const&) ()
   from /home/dreamer/.Rack2/plugins-lin-x64/Biset/plugin.so
#1  0x00007ffff73c55be in rack::widget::EventState::handleKey(rack::math::Vec, int, int, int, int) ()
   from ./libRack.so
#2  0x00007ffff736f715 in ?? () from ./libRack.so
#3  0x00007ffff741b02f in _glfwPollEventsX11 () from ./libRack.so
#4  0x00007ffff7371a44 in rack::window::Window::step() () from ./libRack.so
#5  0x00007ffff7372348 in rack::window::Window::run() () from ./libRack.so
#6  0x0000000000403e65 in main ()
```

**Comment by gibbonjoyeux** [comment]
Thanks for your report !
The bug was reported a few days ago so I sent an update to VCV library but it's not available yet.
Sorry about that, it was a one line bug.

To avoid this issue, you can simply create a pattern in the timeline view before doing anything while the Tracker is selected

**Comment by dromer** [comment]
Ah cool, glad this was already solved :)
